### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by Emerson-git** [Emer17/uffsdb#1]
@thebluenile Conseguiu fazer algum select no banco?

**Comment by ghost** [comment]
@Emer17 Na verdade só o SELECT \* FROM <Tabela>; que é o único tipo de SELECT que tem implementado. Não tá funcionando pra você?

**Comment by Emerson-git** [comment]
@thebluenile essa é a questão... achei que haviam mais alguns tipos implementados... mas ai olhei o readme e percebi que nao tem...

**Comment by Emerson-git** [comment]
Alguem online?

**Comment by Emerson-git** [comment]
Favor verificarem os erros e, se quiserem, atualizar o arquivo erros.docx...
vou envia-lo amanhã a noite..

**Comment by ghost** [comment]
@Emer17  Na descrição do Moodle diz:
"Entrega: um **txt** com o repositório para eu clonar e testar, os membros da equipe e relação de erros com a identificação se foram consertados ou não"

Só que você está para enviar um arquivo **.docx**?

**Comment by Emerson-git** [comment]
eu ia fazer um pdf na verdade..kkk

**Comment by Emerson-git** [comment]
Alem dos erros corrigidos e nao corrigidos, a gente poderia colocar "melhorias" nesse txt. tipo eses vazamentos de memoria que voce corrigiu...  me mande a lista de melhorias que eu arrumo ali.

**Comment by Andreluiz04** [comment]
Não consegui fazer nada por isso se querem me tirar do grupo pode fazer. Prometo que ajudo no próximo.
Abraço.

Date: Sun, 1 May 2016 06:31:22 -0700

**Comment by ghost** [comment]
@Emer17 Eu coloquei lá melhorias no txt também
@Andreluiz04 Relaxa, cada um fez o que conseguiu, não precisa pegar pesado consigo mesmo.

Acho melhor fechar esse "Issue", até porque a idéia não é usar essa funcionalidade como chat :)
